/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task Manager API
 * A simple task management API built with Go and Gin.
 * OpenAPI spec version: 1.0
 */

export interface TaskManagerInternalResponseResponse {
  data?: unknown;
  error?: string;
  status?: number;
}
