/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task Manager API
 * A simple task management API built with Go and Gin.
 * OpenAPI spec version: 1.0
 */
import type { TaskManagerInternalResponseResponse } from "./taskManagerInternalResponseResponse";
import type { CreateTask201AllOf } from "./createTask201AllOf";

export type CreateTask201 = TaskManagerInternalResponseResponse &
  CreateTask201AllOf;
