/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task Manager API
 * A simple task management API built with Go and Gin.
 * OpenAPI spec version: 1.0
 */
import type { TaskManagerInternalResponseResponse } from "./taskManagerInternalResponseResponse";
import type { GetTasks200AllOf } from "./getTasks200AllOf";

export type GetTasks200 = TaskManagerInternalResponseResponse &
  GetTasks200AllOf;
