/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task Manager API
 * A simple task management API built with Go and Gin.
 * OpenAPI spec version: 1.0
 */
import type { TaskManagerInternalResponseResponse } from "./taskManagerInternalResponseResponse";
import type { GetTasksId200AllOf } from "./getTasksId200AllOf";

export type GetTasksId200 = TaskManagerInternalResponseResponse &
  GetTasksId200AllOf;
