/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task Manager API
 * A simple task management API built with Go and Gin.
 * OpenAPI spec version: 1.0
 */

export * from "./getTasks200";
export * from "./getTasks200AllOf";
export * from "./getTasksId200";
export * from "./getTasksId200AllOf";
export * from "./modelTask";
export * from "./modelTaskStatus";
export * from "./postTasks201";
export * from "./postTasks201AllOf";
export * from "./putTasksId200";
export * from "./putTasksId200AllOf";
export * from "./taskManagerInternalResponseResponse";
