/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task Manager API
 * A simple task management API built with Go and Gin.
 * OpenAPI spec version: 1.0
 */
import type { TaskManagerInternalResponseResponse } from "./taskManagerInternalResponseResponse";
import type { PutTasksId200AllOf } from "./putTasksId200AllOf";

export type PutTasksId200 = TaskManagerInternalResponseResponse &
  PutTasksId200AllOf;
